workflows:
  ios-release:
    name: NotiF iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: NoTiF

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.notif.bookmark
      vars:
        XCODE_SCHEME: "InstaChat"
      node: 20
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install npm dependencies
        script: npm install

      - name: Install CocoaPods
        script: cd ios && pod install

      - name: Set up code signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          cd ios
          xcode-project build-ipa \
            --workspace "InstaChat.xcworkspace" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
